/*
    **** Challenge ****
    
    Imagine you are going out to do some grocery shopping.
    So you have an array called shoppingList with all the products you want to buy.
    
    Now that you are inside of the shop, you have a basket with all the products from your list, but you want to add a few more.
    
    Create a new array called shoppingBasket, that will be a copy of the shoppingList array, and add some new products into it. 

*/

const shoppingList = ["eggs", "milk", "butter"];

//the spread operator creates a new array and copies the values of the array we specify. If the first array id modified the one generated by the spread is not affected as it is a copy, not a reference to the first array. Can also be used with objects!

let shoppingBasket = [...shoppingList, "soy milk", "cinnamon rolls", "rice crackers"]

console.log(shoppingBasket)